const SELECCIONA_MESA = "SELECCIONA_MESA";
const CAMBIA_ESTADO_MESA = "CAMBIA_ESTADO_MESA";
const INCREMENTA_DINERO_GANADO = "INCREMENTA_DINERO_GANADO";
const AGREGA_PRODUCTO_MESA = "AGREGA_PRODUCTO_MESA";
const ELIMINA_PRODUCTO_MESA = "ELIMINA_PRODUCTO_MESA";

module.exports = {
  SELECCIONA_MESA,
  CAMBIA_ESTADO_MESA,
  INCREMENTA_DINERO_GANADO,
  AGREGA_PRODUCTO_MESA,
  ELIMINA_PRODUCTO_MESA
};
